title: We are smarter than me # your site title
author: Prugio
email: shpimit@kakao.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shpimit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shpimit # replace with your_twitter_username or comment to remove link from footer
github_username:  shpimit # replace with your_github_username or comment to remove link from footer
instagram_username: shpimit # replace with your_instagram_username or comment to remove link from footer
social:
  name: Prugio
  links:
    - https://twitter.com/shpimit
    - https://www.facebook.com/shpimit
    - https://www.linkedin.com/in/shpimit
    - https://plus.google.com/+shpimit
    - https://github.com/shpimit
    - https://keybase.io/shpimit

disqus:
  shortname: shpimit # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
remote_theme: jekyll-sleek
# theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg
  - cmd.htm
  - cmd.html
  - ['blog']

defaults:
  -
    scope:
      path: "" # 이 빈 문자열은 프로젝트의 모든 파일을 의미함
      type: "" # 이전 Jekyll 2.2 에서는 `post`
    values:
      layout: "page"    

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

google_tag_manager: GTM-K5TJMQCZ
